"""
Cartulari — Occitan Stack Documentation Harvester

Fetches READMEs from all Occitan component repositories, applies
sanitization rules to remove private references, and writes structured
documentation to docs/components/.

Sanitization rules applied:
  - Private domain (occitane.guilhem)        → <your-domain>
  - Private IP ranges (10.x, 192.168.x)      → <CLUSTER_IP>
  - Inline secret values                     → <REDACTED>
  - Private registry image references        → ghcr.io/miegjorn/echo-agent:latest
  - OpenBao/Vault URLs with real hostnames   → http://vault:8200

Run: python .github/scripts/cartulari.py
Requires: GH_TOKEN environment variable (read:org scope for miegjorn repos)
"""

import base64
import json
import os
import re
import subprocess
import sys
from pathlib import Path

ORG = "miegjorn"

COMPONENTS = [
    ("Gardian",     "gardian",     "Secret gateway — token validation and credential resolution"),
    ("Fondament",   "fondament",   "Foundation layer — base types and shared interfaces"),
    ("Farga",       "farga",       "Durable memory layer — signals, artifacts, and project context"),
    ("Amassada",    "amassada",    "Context assembler — aggregates Farga signals for agent consumption"),
    ("Charradissa", "charradissa", "Matrix ↔ agent bridge — routes room messages to component agents"),
    ("Cor",         "cor",         "Core services — shared runtime primitives"),
    ("Caissa",      "caissa",      "Deployment layer — Helm charts and ArgoCD configuration"),
]

# Ordered list of (pattern, replacement) sanitization rules.
# Applied in order — more specific rules should come first.
SANITIZATION_RULES = [
    # Private Matrix domain
    (r'occitane\.guilhem', '<your-domain>'),
    # Private IP ranges
    (r'\b10\.\d{1,3}\.\d{1,3}\.\d{1,3}\b',                    '<CLUSTER_IP>'),
    (r'\b192\.168\.\d{1,3}\.\d{1,3}\b',                        '<CLUSTER_IP>'),
    (r'\b172\.(1[6-9]|2\d|3[01])\.\d{1,3}\.\d{1,3}\b',        '<CLUSTER_IP>'),
    # Inline secret/token values — match key: "value" or key = value patterns
    (r'(?i)((?:token|secret|password|api[_-]?key|registration)[_-]?\w*)'
     r'\s*[:=]\s*["\']?[A-Za-z0-9+/=_\-]{20,}["\']?',
     r'\1: <REDACTED>'),
    # Private Docker registry references (keep public ghcr.io/miegjorn/ ones)
    (r'(?<!/miegjorn/)(?:[a-z0-9.-]+\.)?[a-z0-9-]+\.io/[a-z0-9_/-]+:[a-z0-9._-]+',
     'ghcr.io/miegjorn/echo-agent:latest'),
    # OpenBao / Vault URLs with non-generic hostnames
    (r'http://(?!vault\b)[a-z0-9.-]+(?::\d+)?/(v1|ui)',        r'http://vault:8200/\1'),
    # Matrix room IDs (internal)
    (r'![A-Za-z0-9]{10,}:[a-z0-9.-]+',                         '<MATRIX_ROOM_ID>'),
]


def gh_api(path: str) -> dict | None:
    """Call GitHub API via gh CLI. Returns parsed JSON or None on error."""
    result = subprocess.run(
        ["gh", "api", path],
        capture_output=True, text=True
    )
    if result.returncode != 0:
        print(f"  ⚠  gh api {path}: {result.stderr.strip()}", file=sys.stderr)
        return None
    return json.loads(result.stdout)


def fetch_readme(repo: str) -> str | None:
    """Fetch README.md content from a GitHub repository."""
    data = gh_api(f"repos/{ORG}/{repo}/contents/README.md")
    if data is None:
        return None
    try:
        return base64.b64decode(data["content"]).decode("utf-8", errors="replace")
    except (KeyError, Exception) as e:
        print(f"  ⚠  Could not decode {repo}/README.md: {e}", file=sys.stderr)
        return None


def sanitize(text: str) -> str:
    """Apply all sanitization rules to the given text."""
    for pattern, replacement in SANITIZATION_RULES:
        text = re.sub(pattern, replacement, text)
    return text


def write_component_doc(name: str, slug: str, description: str, content: str) -> None:
    """Write sanitized component doc to docs/components/<slug>.md."""
    out_path = Path("docs") / "components" / f"{slug}.md"
    header = (
        f"<!-- Generated by Cartulari — do not edit manually -->\n"
        f"<!-- Source: https://github.com/{ORG}/{name} -->\n\n"
        f"> **{description}**\n\n"
        f"---\n\n"
    )
    out_path.write_text(header + sanitize(content), encoding="utf-8")
    print(f"  ✓  docs/components/{slug}.md")


def write_index(components: list[tuple[str, str, str]]) -> None:
    """Write docs/README.md index."""
    rows = "\n".join(
        f"| [{name}](components/{slug}.md) | {desc} |"
        for name, slug, desc in components
    )
    content = (
        "<!-- Generated by Cartulari — do not edit manually -->\n\n"
        "# Occitan Stack — Component Documentation\n\n"
        "Documentation harvested from component repositories and sanitized for public consumption.\n\n"
        "| Component | Description |\n"
        "|---|---|\n"
        f"{rows}\n\n"
        "---\n\n"
        "*Generated by [Cartulari](../.github/workflows/cartulari.yml). "
        "To refresh, trigger the workflow manually or wait for the weekly run.*\n"
    )
    Path("docs/README.md").write_text(content, encoding="utf-8")
    print("  ✓  docs/README.md")


def main() -> None:
    print("Cartulari — harvesting Occitan component documentation...")

    Path("docs/components").mkdir(parents=True, exist_ok=True)

    fetched = []
    for repo_name, slug, description in COMPONENTS:
        print(f"  Fetching {ORG}/{repo_name}...")
        content = fetch_readme(repo_name)
        if content:
            write_component_doc(repo_name, slug, description, content)
            fetched.append((repo_name, slug, description))
        else:
            print(f"  ✗  Skipped {repo_name} (no README or access error)")

    write_index(fetched)
    print(f"\nDone. {len(fetched)}/{len(COMPONENTS)} components harvested.")
    if len(fetched) < len(COMPONENTS):
        missing = [n for n, _, _ in COMPONENTS if n not in {f[0] for f in fetched}]
        print(f"Missing: {', '.join(missing)}")


if __name__ == "__main__":
    main()
